option(NEST_ASAN "Enable address sanitizer" OFF)
option(NEST_UBSAN "Enable undefined behaviour sanitizer" OFF)

function(nest_enable_sanitizers project_name)
  set(san_flags "")
  if(NEST_ASAN)
    list(APPEND san_flags -fsanitize=address)
  endif()
  if(NEST_UBSAN)
    list(APPEND san_flags -fsanitize=undefined)
  endif()
  if(san_flags)
    string(REPLACE ";" "," san_flags "${san_flags}")
    target_compile_options(${project_name} PRIVATE -fsanitize=${san_flags})
    target_link_options(${project_name} PRIVATE -fsanitize=${san_flags})
  endif()
endfunction()
